engines:
  bundler-audit:
    enabled: true
  coffeelint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby:
      - coffeescript:
  eslint:
    enabled: true
  fixme:
    enabled: true
  rubocop:
    enabled: true
  markdownlint:
    enabled: true

exclude_paths:
  - "**tipuesearch.js"

ratings:
  paths:
    - "**/*"
