name: Build the site
description: Build the site using nanoc

runs:
  using: 'composite'
  steps:
    - name: Checkout submodule
      shell: bash
      run: git submodule update --init --recursive --remote
    - name: Cache install Nix packages
      uses: rikhuijzer/cache-install@c90964bcac3286c8571cb849f7caffb9e8b9cb37
      with:
        key: nix-${{ hashFiles('packages.nix', 'gemset.nix') }}
        nix_file: 'packages.nix'
    - name: Cache Output
      id: cache-output
      uses: actions/cache@v4
      with:
        path: |
          ./tmp/
          ./output/
        key: build-${{ github.ref_name }}
        restore-keys: |
          build-master
    - name: Set environment variable
      shell: bash
      run: "export LANG=en_US.UTF-8"
    - name: Build site
      shell: bash
      run: "bundle exec nanoc --env=prod"
    - name: Run checks
      shell: bash
      run: "bundle exec nanoc --env=prod check --deploy"